services:
  wsrc.db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=WsrcDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - wsrc.db:/var/lib/postgresql/data/

  messaging.rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "wsrc-dev-user"
      RABBITMQ_DEFAULT_PASS: "wsrc-dev-pwd"
    ports:
      - "5672:5672"
      - "15672:15672"

  wsrc.consumer:
    build:
      context: ./service
      dockerfile: Wsrc.Consumer/Dockerfile
    environment:
      - RABBITMQ__HOSTNAME=messaging.rabbitmq
      - RABBITMQ__USERNAME=wsrc-dev-user
      - RABBITMQ__PASSWORD=wsrc-dev-pwd
      - RABBITMQ__PORT=5672
      - DATABASE__POSTGRESEFCORECONNECTIONSTRING=Server=wsrc.db;Database=WsrcDb;User Id=postgres;Password=postgres;TrustServerCertificate=True;IncludeErrorDetail=True
    depends_on:
      messaging.rabbitmq-started:
        condition: service_completed_successfully
      wsrc.db:
        condition: service_started

  wsrc.producer:
    build:
      context: ./service
      dockerfile: Wsrc.Producer/Dockerfile
    environment:
      - RABBITMQ__HOSTNAME=messaging.rabbitmq
      - RABBITMQ__USERNAME=wsrc-dev-user
      - RABBITMQ__PASSWORD=wsrc-dev-pwd
      - RABBITMQ__PORT=5672
      - DATABASE__POSTGRESEFCORECONNECTIONSTRING=Server=wsrc.db;Database=WsrcDb;User Id=postgres;Password=postgres;TrustServerCertificate=True;IncludeErrorDetail=True
      - KICK__PUSHERCONNECTIONSTRING=wss://ws-us2.pusher.com/app/32cbd69e4b950bf97679?protocol=7&client=js&version=8.4.0-rc2&flash=false
    depends_on:
      messaging.rabbitmq-started:
        condition: service_completed_successfully
      wsrc.db:
        condition: service_started

  messaging.rabbitmq-started:
    image: jwilder/dockerize
    depends_on:
      - messaging.rabbitmq
    command: 'dockerize -wait=tcp://messaging.rabbitmq:5672'
