name: Wsrc Actions

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/service/Wsrc.sln
    - name: Build
      run: dotnet build src/service/Wsrc.sln --no-restore 
    - name: Test
      run: dotnet test src/service/Wsrc.sln --no-build --verbosity normal
